-- CreateTable
CREATE TABLE `Clients` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `dealerId` INTEGER NOT NULL DEFAULT -1,
    `tb` VARCHAR(191) NOT NULL,
    `account` VARCHAR(191) NOT NULL,
    `passwd` VARCHAR(191) NOT NULL,
    `used` BIGINT NOT NULL DEFAULT 0,
    `traffic` BIGINT NOT NULL DEFAULT 0,
    `status` INTEGER NOT NULL DEFAULT 1,
    `expireAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updateAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Clients_account_key`(`account`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Clients` ADD CONSTRAINT `Clients_dealerId_fkey` FOREIGN KEY (`dealerId`) REFERENCES `Users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
